Metrics/ClassLength:
  Max: 300

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false


